name: yofardev_captioner
description: "The captioner app."
publish_to: "none"

version: 1.4.3+12

environment:
  sdk: ^3.9.2

dependencies:
  equatable: ^2.0.8
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  path: ^1.9.1
  screen_retriever: ^0.2.0
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  window_manager: ^0.5.1
  http: ^1.6.0
  uuid: ^4.5.2
  archive: ^4.0.7
  desktop_drop: ^0.7.0
  nested: ^1.0.0
  macos_secure_bookmarks: ^0.2.1
  flutter_launcher_icons: ^0.14.4
  image: ^4.7.2
  path_provider: ^2.1.5
  crop_your_image: ^2.0.0
  get_it: ^9.2.0
  logging: ^1.3.0
  json_annotation: ^4.9.0
  flutter_image_compress: ^2.4.0
  intl: ^0.20.2
  timeago: ^3.7.1

dev_dependencies:
  test: ^1.25.8
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lint:
  bloc_test: ^10.0.0
  mockito: ^5.5.1
  fake_async: ^1.3.2


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/scripts/
    - assets/icons/
  
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron/Orbitron-VariableFont_wght.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/logo.png"
  macos:
    generate: true
    image_path: "assets/logo.png"
  linux:
    generate: true
    image_path: "assets/logo.png"

